services:
  _defaults:
    public: false
    autowire: true

  OxidEsales\SecurityModule\FormSecurity\Service\ModuleSettingsServiceInterface:
    class: OxidEsales\SecurityModule\FormSecurity\Service\ModuleSettingsService
    public: true
