imports:
  - { resource: src/Shared/services.yaml }
  - { resource: src/Captcha/services.yaml }
  - { resource: src/PasswordPolicy/services.yaml }
  - { resource: src/Authentication/services.yaml }
  - { resource: src/GraphQL/services.yaml }
  - { resource: src/PasswordReuse/services.yaml }

services:
  _defaults:
    public: false
    autowire: true

  OxidEsales\SecurityModule\Core\Registry:
    class: 'OxidEsales\Eshop\Core\Registry'
    public: true

  OxidEsales\Eshop\Core\Utils:
    factory: ['@OxidEsales\SecurityModule\Core\Registry', 'getUtils']
    public: true
