services:
  _defaults:
    public: false
    autowire: true

  OxidEsales\SecurityModule\Authentication\TwoFactorAuth\Service\ModuleSettingsServiceInterface:
    class: OxidEsales\SecurityModule\Authentication\TwoFactorAuth\Service\ModuleSettingsService

  OxidEsales\SecurityModule\Authentication\TwoFactorAuth\Service\OTP\OTPGeneratorServiceInterface:
    class: OxidEsales\SecurityModule\Authentication\TwoFactorAuth\Service\OTP\OTPGeneratorService

  OxidEsales\SecurityModule\Authentication\TwoFactorAuth\Service\OTP\ExpirationServiceInterface:
    class: OxidEsales\SecurityModule\Authentication\TwoFactorAuth\Service\OTP\ExpirationService

  OxidEsales\SecurityModule\Authentication\TwoFactorAuth\Service\OTP\OTPValidatorServiceInterface:
    class: OxidEsales\SecurityModule\Authentication\TwoFactorAuth\Service\OTP\OTPValidatorService

  OxidEsales\SecurityModule\Authentication\TwoFactorAuth\Service\OTP\OTPAttemptServiceInterface:
    class: OxidEsales\SecurityModule\Authentication\TwoFactorAuth\Service\OTP\OTPAttemptService

  OxidEsales\SecurityModule\Authentication\TwoFactorAuth\Service\OTP\OTPServiceInterface:
    class: OxidEsales\SecurityModule\Authentication\TwoFactorAuth\Service\OTP\OTPService

  OxidEsales\SecurityModule\Authentication\TwoFactorAuth\Infrastructure\Repository\OTPRepositoryInterface:
    class: OxidEsales\SecurityModule\Authentication\TwoFactorAuth\Infrastructure\Repository\OTPRepository

  OxidEsales\SecurityModule\Authentication\TwoFactorAuth\Infrastructure\Provider\Email\EmailFactoryInterface:
    class: OxidEsales\SecurityModule\Authentication\TwoFactorAuth\Infrastructure\Provider\Email\EmailFactory

  OxidEsales\SecurityModule\Authentication\TwoFactorAuth\Infrastructure\Provider\Email\EmailAdapterInterface:
    class: OxidEsales\SecurityModule\Authentication\TwoFactorAuth\Infrastructure\Provider\Email\EmailAdapter
