services:
  _defaults:
    autowire: true
    public: false
    bind:
      OxidEsales\Eshop\Core\UtilsView: '@=service("OxidEsales\\SecurityModule\\Core\\Registry").getUtilsView()'
      OxidEsales\Eshop\Core\Utils: '@=service("OxidEsales\\SecurityModule\\Core\\Registry").getUtils()'
      OxidEsales\Eshop\Core\UtilsServer: '@=service("OxidEsales\\SecurityModule\\Core\\Registry").getUtilsServer()'
      OxidEsales\Eshop\Core\Config: '@=service("OxidEsales\\SecurityModule\\Core\\Registry").getConfig()'

  OxidEsales\SecurityModule\Authentication\TwoFactorAuth\Shop\Controller\TwoFactorAuthController:
    public: true
    tags:
        - { name: 'oxid.view_controller', controller_key: 'oesm_twofactorauth' }

  OxidEsales\SecurityModule\Authentication\TwoFactorAuth\Shop\Controller\AccountSecurityController:
    public: true
    tags:
        - { name: 'oxid.view_controller', controller_key: 'oesm_account_security' }
