imports:
  - { resource: Authentication/TwoFactorAuth/services.yaml }
  - { resource: Storefront/services.yaml }

services:
  _defaults:
    public: false

  OxidEsales\SecurityModule\GraphQL\Shared\NamespaceMapper:
    autowire: false
    tags:
      - { name: graphql_namespace_mapper }
